package com.ttcs.homestay.controller.booking;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.ttcs.homestay.entity.Booking;
import com.ttcs.homestay.entity.BookingRoomChangeHistory;
import com.ttcs.homestay.entity.BookingStatus;
import com.ttcs.homestay.entity.Room;
import com.ttcs.homestay.entity.RoomStatus;
import com.ttcs.homestay.entity.RoomType;
import com.ttcs.homestay.entity.User;
import com.ttcs.homestay.repository.BookingRepository;
import com.ttcs.homestay.repository.BookingRoomChangeHistoryRepository;
import com.ttcs.homestay.repository.RoleRepository;
import com.ttcs.homestay.repository.RoomRepository;
import com.ttcs.homestay.repository.RoomTypeRepository;
import com.ttcs.homestay.repository.UserRepository;
import com.ttcs.homestay.security.JwtTokenService;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = "spring.datasource.url=jdbc:h2:mem:booking_room_change_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1")
@AutoConfigureMockMvc
class BookingRoomChangeIntegrationTest {
    @Autowired private MockMvc mvc;
    @Autowired private BookingRepository bookings;
    @Autowired private BookingRoomChangeHistoryRepository histories;
    @Autowired private RoomRepository rooms;
    @Autowired private RoomTypeRepository roomTypes;
    @Autowired private UserRepository users;
    @Autowired private RoleRepository roles;
    @Autowired private JwtTokenService tokens;
    @Autowired private JdbcTemplate jdbc;
    private RoomType type;
    private Room oldRoom;
    private Room newRoom;
    private Room otherTypeRoom;
    private User receptionist;
    private String receptionistToken;
    private String ownerToken;

    @BeforeEach
    void setUp() {
        jdbc.update("DELETE FROM booking_deposits");
        histories.deleteAll();
        bookings.deleteAll();
        rooms.deleteAll();
        roomTypes.deleteAll();
        users.deleteAll();
        roles.deleteAll();
        jdbc.update("CREATE TABLE IF NOT EXISTS booking_room_change_history ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE, "
                + "old_room_id BIGINT NOT NULL REFERENCES rooms(id), new_room_id BIGINT NOT NULL REFERENCES rooms(id), "
                + "actor_user_id BIGINT NOT NULL REFERENCES users(id), changed_at TIMESTAMP WITH TIME ZONE NOT NULL, reason VARCHAR(500) NOT NULL, "
                + "CONSTRAINT booking_room_change_history_distinct_rooms CHECK (old_room_id <> new_room_id), "
                + "CONSTRAINT booking_room_change_history_reason_nonblank CHECK (LENGTH(TRIM(reason)) > 0))");
        receptionistToken = createUser("RECEPTIONIST", "Receptionist");
        ownerToken = createUser("OWNER", "Owner");
        type = roomType("RC-" + suffix());
        RoomType anotherType = roomType("OTHER-" + suffix());
        oldRoom = room("801", type);
        newRoom = room("802", type);
        otherTypeRoom = room("803", anotherType);
    }

    @Test
    void apiChangesRoomAndReturnsPersistedHistoryIncludingCheckInDay() throws Exception {
        Booking booking = booking("BK-RC-" + suffix(), LocalDate.now(), BookingStatus.DA_XAC_NHAN,
                oldRoom, true);
        mvc.perform(put("/api/bookings/{id}/room-change", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"  Leak repair  \"}"))
                .andExpect(status().isOk());
        Booking updated = bookings.findById(booking.getId()).orElseThrow();
        assertThat(updated.getRoom().getId()).isEqualTo(newRoom.getId());
        BookingRoomChangeHistory row = histories.findAllByBookingIdOrderByChangedAtDescIdDesc(booking.getId()).get(0);
        assertThat(row.getOldRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(row.getNewRoom().getId()).isEqualTo(newRoom.getId());
        assertThat(row.getActor().getId()).isEqualTo(receptionist.getId());
        assertThat(row.getChangedAt()).isNotNull();
        assertThat(row.getReason()).isEqualTo("Leak repair");
        mvc.perform(get("/api/bookings/{id}/room-change-history", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].oldRoomNumber").value("801"))
                .andExpect(jsonPath("$[0].newRoomNumber").value("802"))
                .andExpect(jsonPath("$[0].actorUserId").value(receptionist.getId()))
                .andExpect(jsonPath("$[0].reason").value("Leak repair"));
    }

    @Test
    void invalidRoomReasonAndStatusLeaveBookingAndHistoryUnchanged() throws Exception {
        Booking target = booking("BK-RC-T-" + suffix(), LocalDate.now().plusDays(3),
                BookingStatus.DA_XAC_NHAN, oldRoom, true);
        Booking conflict = booking("BK-RC-C-" + suffix(), target.getCheckInDate(),
                BookingStatus.DA_XAC_NHAN, newRoom, true);
        assertRejected(target, newRoom.getId(), "Repair", 409);
        assertRejected(target, otherTypeRoom.getId(), "Repair", 409);
        assertRejected(target, newRoom.getId(), "  ", 400);
        assertRejected(target, newRoom.getId(), "Repair", 409, BookingStatus.DA_TRA_PHONG);
        assertThat(bookings.findById(target.getId()).orElseThrow().getRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(bookings.findById(conflict.getId()).orElseThrow().getRoom().getId()).isEqualTo(newRoom.getId());
        assertThat(histories.count()).isZero();
    }

    @Test
    void receptionistCanChangeAndReadHistoryOwnerCanReadButCannotChange() throws Exception {
        Booking target = booking("BK-RC-P-" + suffix(), LocalDate.now().plusDays(4),
                BookingStatus.DA_XAC_NHAN, oldRoom, true);
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + ownerToken)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"Repair\"}"))
                .andExpect(status().isForbidden());
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"Repair\"}"))
                .andExpect(status().isOk());
        mvc.perform(get("/api/bookings/{id}/room-change-history", target.getId())
                        .header("Authorization", "Bearer " + ownerToken))
                .andExpect(status().isOk());
        assertThat(histories.count()).isEqualTo(1);
    }

    private Booking checkedInBooking() {
        oldRoom.setStatus(RoomStatus.DANG_O);
        rooms.saveAndFlush(oldRoom);
        return booking("AC4-" + suffix(), LocalDate.now(java.time.ZoneId.of("Asia/Ho_Chi_Minh")).minusDays(1),
                BookingStatus.DA_NHAN_PHONG, oldRoom, true);
    }

    private org.springframework.test.web.servlet.ResultActions change(Booking booking, String token) throws Exception {
        return mvc.perform(put("/api/bookings/{id}/room-change", booking.getId())
                .header("Authorization", "Bearer " + token).contentType(MediaType.APPLICATION_JSON)
                .content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"  Repair  \"}"));
    }

    private void assertUnchanged(Booking booking) {
        assertThat(bookings.findById(booking.getId()).orElseThrow().getRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(rooms.findById(oldRoom.getId()).orElseThrow().getStatus()).isEqualTo(RoomStatus.DANG_O);
        assertThat(histories.count()).isZero();
    }

    @Test
    void checkedInChangePersistsRoomsBookingAndHistoryAcrossRequests() throws Exception {
        Booking booking = checkedInBooking();
        jdbc.update("INSERT INTO booking_deposits (booking_id, amount, payment_method, created_at) VALUES (?, 50000, 'CASH', CURRENT_TIMESTAMP)", booking.getId());
        change(booking, receptionistToken).andExpect(status().isOk());
        Booking saved = bookings.findById(booking.getId()).orElseThrow();
        assertThat(saved.getStatus()).isEqualTo(BookingStatus.DA_NHAN_PHONG);
        assertThat(saved.getRoom().getId()).isEqualTo(newRoom.getId());
        assertThat(saved.getTotalAmount()).isEqualTo(booking.getTotalAmount());
        assertThat(saved.getWeekdayPriceSnapshot()).isEqualTo(booking.getWeekdayPriceSnapshot());
        assertThat(saved.getWeekendPriceSnapshot()).isEqualTo(booking.getWeekendPriceSnapshot());
        assertThat(saved.getCheckInDate()).isEqualTo(booking.getCheckInDate());
        assertThat(saved.getCheckOutDate()).isEqualTo(booking.getCheckOutDate());
        assertThat(jdbc.queryForObject("SELECT amount FROM booking_deposits WHERE booking_id = ?", java.math.BigDecimal.class, booking.getId()))
                .isEqualByComparingTo("50000");
        assertThat(rooms.findById(oldRoom.getId()).orElseThrow().getStatus()).isEqualTo(RoomStatus.TRONG_BAN);
        assertThat(rooms.findById(newRoom.getId()).orElseThrow().getStatus()).isEqualTo(RoomStatus.DANG_O);
        mvc.perform(get("/api/bookings/{id}/room-change-history", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk()).andExpect(jsonPath("$[0].reason").value("Repair"))
                .andExpect(jsonPath("$[0].oldRoomId").value(oldRoom.getId()))
                .andExpect(jsonPath("$[0].newRoomId").value(newRoom.getId()))
                .andExpect(jsonPath("$[0].actorUserId").value(receptionist.getId()))
                .andExpect(jsonPath("$[0].changedAt").isNotEmpty());
        mvc.perform(get("/api/bookings").param("status", "DA_NHAN_PHONG")
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk()).andExpect(jsonPath("$.content[0].status").value("DA_NHAN_PHONG"))
                .andExpect(jsonPath("$.content[0].roomNumber").value("802"));
    }

    @Test
    void checkedInRejectsUnavailableRoomsAndInvalidInputs() throws Exception {
        Booking booking = checkedInBooking();
        for (RoomStatus roomStatus : java.util.List.of(RoomStatus.TRONG_BAN, RoomStatus.DANG_O, RoomStatus.BAO_TRI)) {
            newRoom.setStatus(roomStatus);
            rooms.saveAndFlush(newRoom);
            change(booking, receptionistToken).andExpect(status().isConflict());
            assertUnchanged(booking);
            assertThat(rooms.findById(newRoom.getId()).orElseThrow().getStatus()).isEqualTo(roomStatus);
        }
        newRoom.setStatus(RoomStatus.TRONG_SACH);
        rooms.saveAndFlush(newRoom);
        assertRejected(booking, otherTypeRoom.getId(), "Repair", 409);
        assertRejected(booking, oldRoom.getId(), "Repair", 409);
        assertRejected(booking, newRoom.getId(), "  ", 400);
        assertRejected(booking, newRoom.getId(), "\u2003\u00a0", 400);
        assertRejected(booking, newRoom.getId(), "Repair", 409, BookingStatus.DA_TRA_PHONG);
        oldRoom.setStatus(RoomStatus.TRONG_BAN);
        rooms.saveAndFlush(oldRoom);
        change(booking, receptionistToken).andExpect(status().isConflict());
    }

    @Test
    void checkedInRejectsEveryNonReceptionistRole() throws Exception {
        Booking booking = checkedInBooking();
        for (String role : java.util.List.of("OWNER", "ADMIN", "HOUSEKEEPING")) {
            change(booking, createUser(role, role)).andExpect(status().isForbidden());
        }
        assertUnchanged(booking);
    }

    @Test
    void availableRoomsAndConfirmationRespectRemainingStayAndV36IncludingExpiredHolds() throws Exception {
        Booking booking = checkedInBooking();
        mvc.perform(get("/api/bookings/{id}/available-rooms", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].id").value(newRoom.getId()));
        Booking conflict = booking("CONFLICT-" + suffix(), booking.getCheckInDate(),
                BookingStatus.DA_XAC_NHAN, newRoom, true);
        change(booking, receptionistToken).andExpect(status().isConflict());
        // Only the past part overlaps: remaining-stay validation passes, V36 must still reject.
        conflict.setCheckOutDate(LocalDate.now(java.time.ZoneId.of("Asia/Ho_Chi_Minh")));
        bookings.saveAndFlush(conflict);
        change(booking, receptionistToken).andExpect(status().isConflict());
        conflict.setStatus(BookingStatus.CHO_XAC_NHAN);
        conflict.setHoldExpiresAt(OffsetDateTime.now().minusDays(2));
        bookings.saveAndFlush(conflict);
        change(booking, receptionistToken).andExpect(status().isConflict());
        mvc.perform(get("/api/bookings/{id}/available-rooms", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(0));
        assertUnchanged(booking);
    }

    @Test
    void historyFailureRollsBackAlreadyFlushedBookingAndBothRooms() throws Exception {
        Booking booking = checkedInBooking();
        jdbc.execute("ALTER TABLE booking_room_change_history ADD CONSTRAINT ac4_test_failure CHECK (reason <> 'Repair')");
        try {
            try {
                change(booking, receptionistToken).andExpect(status().is5xxServerError());
            } catch (jakarta.servlet.ServletException expected) {
                assertThat(expected).hasRootCauseInstanceOf(java.sql.SQLException.class);
            }
            assertUnchanged(booking);
            assertThat(rooms.findById(newRoom.getId()).orElseThrow().getStatus()).isEqualTo(RoomStatus.TRONG_SACH);
        } finally {
            jdbc.execute("ALTER TABLE booking_room_change_history DROP CONSTRAINT ac4_test_failure");
        }
    }

    private void assertRejected(Booking target, long roomId, String reason, int expected) throws Exception {
        assertRejected(target, roomId, reason, expected, target.getStatus());
    }

    private void assertRejected(Booking target, long roomId, String reason, int expected, BookingStatus status) throws Exception {
        BookingStatus original = target.getStatus();
        target.setStatus(status);
        bookings.saveAndFlush(target);
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":" + roomId + ",\"reason\":" +
                                new tools.jackson.databind.ObjectMapper().writeValueAsString(reason) + "}"))
                .andExpect(status().is(expected));
        target.setStatus(original);
        bookings.saveAndFlush(target);
        assertThat(bookings.findById(target.getId()).orElseThrow().getRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(histories.count()).isZero();
    }

    private String createUser(String roleCode, String name) {
        var role = roles.findByCode(roleCode).orElseGet(() -> {
            jdbc.update("INSERT INTO roles (code, name) VALUES (?, ?)", roleCode, name);
            return roles.findByCode(roleCode).orElseThrow();
        });
        User user = User.createStaff(name, roleCode.toLowerCase() + "-" + suffix() + "@test.local", null, role, true, "hash");
        user.changePassword("test-hash");
        user = users.saveAndFlush(user);
        if (roleCode.equals("RECEPTIONIST")) receptionist = user;
        return tokens.issueTokens(user).accessToken();
    }

    private RoomType roomType(String name) {
        RoomType value = new RoomType(); value.setCode(name); value.setName(name);
        value.setStandardCapacity(2); value.setMaxCapacity(2); value.setNumberOfBeds(1);
        return roomTypes.saveAndFlush(value);
    }

    private Room room(String number, RoomType type) {
        Room value = new Room(); value.setRoomNumber(number); value.setFloor(8); value.setRoomType(type.getName());
        value.setStatus(RoomStatus.TRONG_SACH); value.setActive(true);
        return rooms.saveAndFlush(value);
    }

    private Booking booking(String code, LocalDate checkIn, BookingStatus status, Room room, boolean confirmed) {
        Booking value = new Booking(); value.setRoomType(type); value.setRoom(room); value.setRoomTypeNameSnapshot(type.getName());
        value.setCheckInDate(checkIn); value.setCheckOutDate(checkIn.plusDays(2));
        value.setWeekdayPriceSnapshot(100_000); value.setWeekendPriceSnapshot(100_000); value.setWeekendDaysSnapshot("SATURDAY,SUNDAY");
        value.setTotalAmount(200_000); value.setCreatedAt(OffsetDateTime.now()); value.setBookingCode(code); value.setGuestName("Guest"); value.setStatus(status);
        Booking saved = bookings.saveAndFlush(value);
        if (confirmed) { saved.setRoomConfirmedAt(OffsetDateTime.now()); saved.setRoomConfirmedByUser(receptionist); return bookings.saveAndFlush(saved); }
        return saved;
    }

    private String suffix() { return UUID.randomUUID().toString().substring(0, 8); }
}
