package com.ttcs.homestay.controller.booking;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.ttcs.homestay.entity.Booking;
import com.ttcs.homestay.entity.BookingRoomChangeHistory;
import com.ttcs.homestay.entity.BookingStatus;
import com.ttcs.homestay.entity.Room;
import com.ttcs.homestay.entity.RoomStatus;
import com.ttcs.homestay.entity.RoomType;
import com.ttcs.homestay.entity.User;
import com.ttcs.homestay.repository.BookingRepository;
import com.ttcs.homestay.repository.BookingRoomChangeHistoryRepository;
import com.ttcs.homestay.repository.RoleRepository;
import com.ttcs.homestay.repository.RoomRepository;
import com.ttcs.homestay.repository.RoomTypeRepository;
import com.ttcs.homestay.repository.UserRepository;
import com.ttcs.homestay.security.JwtTokenService;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = "spring.datasource.url=jdbc:h2:mem:booking_room_change_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1")
@AutoConfigureMockMvc
class BookingRoomChangeIntegrationTest {
    @Autowired private MockMvc mvc;
    @Autowired private BookingRepository bookings;
    @Autowired private BookingRoomChangeHistoryRepository histories;
    @Autowired private RoomRepository rooms;
    @Autowired private RoomTypeRepository roomTypes;
    @Autowired private UserRepository users;
    @Autowired private RoleRepository roles;
    @Autowired private JwtTokenService tokens;
    @Autowired private JdbcTemplate jdbc;
    private RoomType type;
    private Room oldRoom;
    private Room newRoom;
    private Room otherTypeRoom;
    private User receptionist;
    private String receptionistToken;
    private String ownerToken;

    @BeforeEach
    void setUp() {
        histories.deleteAll();
        bookings.deleteAll();
        rooms.deleteAll();
        roomTypes.deleteAll();
        users.deleteAll();
        roles.deleteAll();
        jdbc.update("CREATE TABLE IF NOT EXISTS booking_room_change_history ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE, "
                + "old_room_id BIGINT NOT NULL REFERENCES rooms(id), new_room_id BIGINT NOT NULL REFERENCES rooms(id), "
                + "actor_user_id BIGINT NOT NULL REFERENCES users(id), changed_at TIMESTAMP WITH TIME ZONE NOT NULL, reason VARCHAR(500) NOT NULL, "
                + "CONSTRAINT booking_room_change_history_distinct_rooms CHECK (old_room_id <> new_room_id), "
                + "CONSTRAINT booking_room_change_history_reason_nonblank CHECK (LENGTH(TRIM(reason)) > 0))");
        receptionistToken = createUser("RECEPTIONIST", "Receptionist");
        ownerToken = createUser("OWNER", "Owner");
        type = roomType("RC-" + suffix());
        RoomType anotherType = roomType("OTHER-" + suffix());
        oldRoom = room("801", type);
        newRoom = room("802", type);
        otherTypeRoom = room("803", anotherType);
    }

    @Test
    void apiChangesRoomAndReturnsPersistedHistoryIncludingCheckInDay() throws Exception {
        Booking booking = booking("BK-RC-" + suffix(), LocalDate.now(), BookingStatus.DA_XAC_NHAN,
                oldRoom, true);
        mvc.perform(put("/api/bookings/{id}/room-change", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"  Leak repair  \"}"))
                .andExpect(status().isOk());
        Booking updated = bookings.findById(booking.getId()).orElseThrow();
        assertThat(updated.getRoom().getId()).isEqualTo(newRoom.getId());
        BookingRoomChangeHistory row = histories.findAllByBookingIdOrderByChangedAtDescIdDesc(booking.getId()).get(0);
        assertThat(row.getOldRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(row.getNewRoom().getId()).isEqualTo(newRoom.getId());
        assertThat(row.getActor().getId()).isEqualTo(receptionist.getId());
        assertThat(row.getChangedAt()).isNotNull();
        assertThat(row.getReason()).isEqualTo("Leak repair");
        mvc.perform(get("/api/bookings/{id}/room-change-history", booking.getId())
                        .header("Authorization", "Bearer " + receptionistToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].oldRoomNumber").value("801"))
                .andExpect(jsonPath("$[0].newRoomNumber").value("802"))
                .andExpect(jsonPath("$[0].actorUserId").value(receptionist.getId()))
                .andExpect(jsonPath("$[0].reason").value("Leak repair"));
    }

    @Test
    void invalidRoomReasonAndStatusLeaveBookingAndHistoryUnchanged() throws Exception {
        Booking target = booking("BK-RC-T-" + suffix(), LocalDate.now().plusDays(3),
                BookingStatus.DA_XAC_NHAN, oldRoom, true);
        Booking conflict = booking("BK-RC-C-" + suffix(), target.getCheckInDate(),
                BookingStatus.DA_XAC_NHAN, newRoom, true);
        assertRejected(target, newRoom.getId(), "Repair", 409);
        assertRejected(target, otherTypeRoom.getId(), "Repair", 409);
        assertRejected(target, newRoom.getId(), "  ", 400);
        assertRejected(target, newRoom.getId(), "Repair", 409, BookingStatus.DA_NHAN_PHONG);
        assertThat(bookings.findById(target.getId()).orElseThrow().getRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(bookings.findById(conflict.getId()).orElseThrow().getRoom().getId()).isEqualTo(newRoom.getId());
        assertThat(histories.count()).isZero();
    }

    @Test
    void receptionistCanChangeAndReadHistoryOwnerCanReadButCannotChange() throws Exception {
        Booking target = booking("BK-RC-P-" + suffix(), LocalDate.now().plusDays(4),
                BookingStatus.DA_XAC_NHAN, oldRoom, true);
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + ownerToken)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"Repair\"}"))
                .andExpect(status().isForbidden());
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"roomId\":" + newRoom.getId() + ",\"reason\":\"Repair\"}"))
                .andExpect(status().isOk());
        mvc.perform(get("/api/bookings/{id}/room-change-history", target.getId())
                        .header("Authorization", "Bearer " + ownerToken))
                .andExpect(status().isOk());
        assertThat(histories.count()).isEqualTo(1);
    }

    private void assertRejected(Booking target, long roomId, String reason, int expected) throws Exception {
        assertRejected(target, roomId, reason, expected, target.getStatus());
    }

    private void assertRejected(Booking target, long roomId, String reason, int expected, BookingStatus status) throws Exception {
        BookingStatus original = target.getStatus();
        target.setStatus(status);
        bookings.saveAndFlush(target);
        mvc.perform(put("/api/bookings/{id}/room-change", target.getId())
                        .header("Authorization", "Bearer " + receptionistToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":" + roomId + ",\"reason\":" +
                                new tools.jackson.databind.ObjectMapper().writeValueAsString(reason) + "}"))
                .andExpect(status().is(expected));
        target.setStatus(original);
        bookings.saveAndFlush(target);
        assertThat(bookings.findById(target.getId()).orElseThrow().getRoom().getId()).isEqualTo(oldRoom.getId());
        assertThat(histories.count()).isZero();
    }

    private String createUser(String roleCode, String name) {
        var role = roles.findByCode(roleCode).orElseGet(() -> {
            jdbc.update("INSERT INTO roles (code, name) VALUES (?, ?)", roleCode, name);
            return roles.findByCode(roleCode).orElseThrow();
        });
        User user = User.createStaff(name, roleCode.toLowerCase() + "-" + suffix() + "@test.local", null, role, true, "hash");
        user.changePassword("test-hash");
        user = users.saveAndFlush(user);
        if (roleCode.equals("RECEPTIONIST")) receptionist = user;
        return tokens.issueTokens(user).accessToken();
    }

    private RoomType roomType(String name) {
        RoomType value = new RoomType(); value.setCode(name); value.setName(name);
        value.setStandardCapacity(2); value.setMaxCapacity(2); value.setNumberOfBeds(1);
        return roomTypes.saveAndFlush(value);
    }

    private Room room(String number, RoomType type) {
        Room value = new Room(); value.setRoomNumber(number); value.setFloor(8); value.setRoomType(type.getName());
        value.setStatus(RoomStatus.TRONG_SACH); value.setActive(true);
        return rooms.saveAndFlush(value);
    }

    private Booking booking(String code, LocalDate checkIn, BookingStatus status, Room room, boolean confirmed) {
        Booking value = new Booking(); value.setRoomType(type); value.setRoom(room); value.setRoomTypeNameSnapshot(type.getName());
        value.setCheckInDate(checkIn); value.setCheckOutDate(checkIn.plusDays(2));
        value.setWeekdayPriceSnapshot(100_000); value.setWeekendPriceSnapshot(100_000); value.setWeekendDaysSnapshot("SATURDAY,SUNDAY");
        value.setTotalAmount(200_000); value.setCreatedAt(OffsetDateTime.now()); value.setBookingCode(code); value.setGuestName("Guest"); value.setStatus(status);
        Booking saved = bookings.saveAndFlush(value);
        if (confirmed) { saved.setRoomConfirmedAt(OffsetDateTime.now()); saved.setRoomConfirmedByUser(receptionist); return bookings.saveAndFlush(saved); }
        return saved;
    }

    private String suffix() { return UUID.randomUUID().toString().substring(0, 8); }
}
