package com.ttcs.homestay.config;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Khởi tạo dữ liệu mẫu khi chạy hồ sơ test / H2 in-memory.
 */
@Component
@Profile("test")
public class H2DevDataLoader implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;
    private final org.springframework.security.crypto.password.PasswordEncoder passwordEncoder;

    public H2DevDataLoader(JdbcTemplate jdbcTemplate, org.springframework.security.crypto.password.PasswordEncoder passwordEncoder) {
        this.jdbcTemplate = jdbcTemplate;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(ApplicationArguments args) {
        // 1. Tạo bảng audit_logs nếu chưa tồn tại (H2 dev)
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS audit_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                actor_user_id BIGINT,
                actor_email VARCHAR(255),
                user_id BIGINT,
                account_email VARCHAR(255),
                action VARCHAR(100) NOT NULL,
                result VARCHAR(20) NOT NULL,
                ip_address VARCHAR(45),
                occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """);

        // 2. Khởi tạo roles
        Integer roleCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM roles", Integer.class);
        if (roleCount == null || roleCount == 0) {
            jdbcTemplate.execute("""
                INSERT INTO roles (code, name) VALUES
                ('RECEPTIONIST', 'Receptionist'),
                ('HOUSEKEEPING', 'Housekeeping'),
                ('OWNER', 'Owner'),
                ('ADMIN', 'Administrator')
            """);
        }

        // 3. Khởi tạo tài khoản quản trị mẫu: admin.demo@homestay.local / password
        Long adminRoleId = jdbcTemplate.queryForObject("SELECT id FROM roles WHERE code = 'ADMIN'", Long.class);
        Integer adminCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM users WHERE email = 'admin.demo@homestay.local'", Integer.class);
        String demoPasswordHash = passwordEncoder.encode("password");
        if (adminCount == null || adminCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO users (
                    full_name, email, password_hash, role_id, is_active,
                    failed_login_count, token_version, must_change_password, created_at, updated_at)
                VALUES ('Demo Administrator', 'admin.demo@homestay.local',
                        ?, ?, TRUE, 0, 1, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """, demoPasswordHash, adminRoleId);
        } else {
            jdbcTemplate.update("UPDATE users SET password_hash = ?, failed_login_count = 0, is_active = TRUE WHERE email = 'admin.demo@homestay.local'", demoPasswordHash);
        }

        // 4. Khởi tạo tham số vận hành
        Integer settingsCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM operating_settings", Integer.class);
        if (settingsCount == null || settingsCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO operating_settings (
                    homestay_name, check_in_time, check_out_time, late_checkout_fee_per_hour,
                    extra_person_fee, created_by_name, weekend_days, created_at)
                VALUES ('HomeStay Retreat', '14:00', '12:00', 100000, 200000, 'Hệ thống',
                        'FRIDAY,SATURDAY', CURRENT_TIMESTAMP)
            """);
        }

        // 5. Khởi tạo dữ liệu các loại phòng (gồm cả phòng đang bán và phòng ngừng bán để test S2-04)
        Integer rtCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM room_types", Integer.class);
        if (rtCount == null || rtCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO room_types (code, name, standard_capacity, max_capacity, number_of_beds, description, status, weekday_price, weekend_price)
                VALUES
                ('DON', 'Phòng đơn', 1, 2, 1, 'Phòng đơn ấm cúng, thiết kế tối giản tinh tế với bàn làm việc và cửa sổ hướng vườn.', TRUE, 300000, 400000),
                ('DOI', 'Phòng đôi', 2, 3, 1, 'Phòng đôi sang trọng với giường Queen êm ái, ánh sáng tự nhiên ngập tràn và không gian thư giãn hoàn hảo.', TRUE, 500000, 650000),
                ('GIA_DINH', 'Phòng gia đình', 4, 5, 2, 'Phòng gia đình rộng rãi gồm 2 giường đôi lớn, ban công thoáng mát và khu vực sinh hoạt chung ấm cúng.', TRUE, 900000, 1200000),
                ('VIP', 'Phòng VIP cũ (Đã ngừng bán)', 2, 2, 1, 'Loại phòng VIP trước đây, hiện đã ngừng kinh doanh để nâng cấp.', FALSE, 1000000, 1500000)
            """);
        }

        // 6. Khởi tạo tiện nghi và bảng nối room_type_amenities
        Integer amenityCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM amenities", Integer.class);
        if (amenityCount == null || amenityCount == 0) {
            jdbcTemplate.execute("""
                INSERT INTO amenities (id, code, name, icon, active) VALUES
                (1, 'DIEU_HOA',  'Điều hoà 2 chiều',    '❄️', TRUE),
                (2, 'WIFI',      'Wi-Fi tốc độ cao',    '📶', TRUE),
                (3, 'BAN_CONG',  'Ban công view đẹp',   '🌇', TRUE),
                (4, 'TIVI',      'Tivi màn hình phẳng', '📺', TRUE),
                (5, 'NONG_LANH', 'Bình nóng lạnh',      '🚿', TRUE),
                (6, 'TU_LANH',   'Tủ lạnh mini',        '🧊', TRUE)
            """);

            jdbcTemplate.execute("""
                INSERT INTO room_type_amenities (room_type_id, amenity_id)
                SELECT rt.id, a.id FROM room_types rt CROSS JOIN amenities a
                WHERE (rt.code = 'DON' AND a.code IN ('DIEU_HOA', 'WIFI', 'NONG_LANH'))
                   OR (rt.code = 'DOI' AND a.code IN ('DIEU_HOA', 'WIFI', 'TIVI', 'NONG_LANH', 'TU_LANH'))
                   OR (rt.code = 'GIA_DINH' AND a.code IN ('DIEU_HOA', 'WIFI', 'TIVI', 'NONG_LANH', 'TU_LANH', 'BAN_CONG'))
            """);
        }

        // 7. Khởi tạo danh sách phòng mẫu
        Integer roomCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM rooms", Integer.class);
        if (roomCount == null || roomCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO rooms (room_number, floor, room_type, status, active)
                VALUES
                ('101', 1, 'Phòng đơn', 'TRONG_SACH', TRUE),
                ('102', 1, 'Phòng đôi', 'TRONG_SACH', TRUE),
                ('201', 2, 'Phòng đôi', 'TRONG_SACH', TRUE),
                ('301', 3, 'Phòng gia đình', 'TRONG_SACH', TRUE)
            """);
        }
    }
}
