package com.ttcs.homestay.config;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Profile({"test", "dev"})
public class H2DevDataLoader implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;
    private final org.springframework.security.crypto.password.PasswordEncoder passwordEncoder;

    public H2DevDataLoader(JdbcTemplate jdbcTemplate, org.springframework.security.crypto.password.PasswordEncoder passwordEncoder) {
        this.jdbcTemplate = jdbcTemplate;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(ApplicationArguments args) {
        // 1. Tạo bảng audit_logs nếu chưa tồn tại (H2 dev)
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS audit_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                actor_user_id BIGINT,
                actor_email VARCHAR(255),
                user_id BIGINT,
                account_email VARCHAR(255),
                action VARCHAR(100) NOT NULL,
                result VARCHAR(20) NOT NULL,
                ip_address VARCHAR(45),
                occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """);

        // 2. Khởi tạo roles
        Integer roleCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM roles", Integer.class);
        if (roleCount == null || roleCount == 0) {
            jdbcTemplate.execute("""
                INSERT INTO roles (code, name) VALUES
                ('RECEPTIONIST', 'Receptionist'),
                ('HOUSEKEEPING', 'Housekeeping'),
                ('OWNER', 'Owner'),
                ('ADMIN', 'Administrator')
            """);
        }

        // 3. Khởi tạo tài khoản quản trị mẫu: admin.demo@homestay.local / password
        Long adminRoleId = jdbcTemplate.queryForObject("SELECT id FROM roles WHERE code = 'ADMIN'", Long.class);
        Integer adminCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM users WHERE email = 'admin.demo@homestay.local'", Integer.class);
        String demoPasswordHash = passwordEncoder.encode("password");
        if (adminCount == null || adminCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO users (
                    full_name, email, password_hash, role_id, is_active,
                    failed_login_count, token_version, must_change_password, created_at, updated_at)
                VALUES ('Demo Administrator', 'admin.demo@homestay.local',
                        ?, ?, TRUE, 0, 1, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """, demoPasswordHash, adminRoleId);
        } else {
            jdbcTemplate.update("UPDATE users SET password_hash = ?, failed_login_count = 0, is_active = TRUE WHERE email = 'admin.demo@homestay.local'", demoPasswordHash);
        }

        // 4. Khởi tạo tham số vận hành
        Integer settingsCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM operating_settings", Integer.class);
        if (settingsCount == null || settingsCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO operating_settings (
                    homestay_name, check_in_time, check_out_time, late_checkout_fee_per_hour,
                    extra_person_fee, created_by_name, weekend_days, created_at)
                VALUES ('HomeStay Retreat', '14:00', '12:00', 100000, 200000, 'Hệ thống',
                        'FRIDAY,SATURDAY', CURRENT_TIMESTAMP)
            """);

            Long defaultSettingsId = jdbcTemplate.queryForObject(
                    "SELECT id FROM operating_settings ORDER BY id ASC LIMIT 1", Long.class);
            if (defaultSettingsId != null) {
                jdbcTemplate.update("""
                    INSERT INTO cancellation_policy_tiers (settings_id, hours_before_check_in, refund_percent)
                    VALUES
                    (?, 72, 100),
                    (?, 24, 50),
                    (?, 0, 0)
                """, defaultSettingsId, defaultSettingsId, defaultSettingsId);
            }
        }

        // 5. Khởi tạo dữ liệu các loại phòng (gồm cả phòng đang bán và phòng ngừng bán để test S2-04)
        Integer rtCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM room_types", Integer.class);
        if (rtCount == null || rtCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO room_types (code, name, standard_capacity, max_capacity, number_of_beds, description, status, weekday_price, weekend_price, check_in_time, check_out_time, allow_children, child_policy, extra_person_fee, cancellation_policy)
                VALUES
                ('DON', 'Phòng đơn', 1, 2, 1, 'Phòng đơn ấm cúng, thiết kế tối giản tinh tế với bàn làm việc và cửa sổ hướng vườn.', TRUE, 300000, 400000, '14:00', '12:00', TRUE, 'Cho phép mang theo trẻ nhỏ. Trẻ dưới 6 tuổi ở cùng người lớn miễn phí.', 150000, 'Chính sách hủy linh hoạt chuẩn homestay'),
                ('DOI', 'Phòng đôi', 2, 3, 1, 'Phòng đôi sang trọng với giường Queen êm ái, ánh sáng tự nhiên ngập tràn và không gian thư giãn hoàn hảo.', TRUE, 500000, 650000, '14:00', '12:00', TRUE, 'Cho phép tối đa 1 trẻ em dưới 6 tuổi ngủ chung giường với bố mẹ miễn phí.', 200000, 'Chính sách hủy tiêu chuẩn hoàn 100% trước 72 giờ'),
                ('GIA_DINH', 'Phòng gia đình', 4, 5, 2, 'Phòng gia đình rộng rãi gồm 2 giường đôi lớn, ban công thoáng mát và khu vực sinh hoạt chung ấm cúng.', TRUE, 900000, 1200000, '14:00', '12:00', TRUE, 'Rất hoan nghênh gia đình có trẻ nhỏ. Hỗ trợ miễn phí cũi em bé nếu đặt trước.', 250000, 'Hủy miễn phí trước 72h cho gia đình'),
                ('STUDIO_ADULT', 'Studio Người Lớn', 2, 2, 1, 'Không gian nghỉ dưỡng biệt lập cao cấp dành riêng cho các cặp đôi hoặc cá nhân cần sự yên tĩnh.', TRUE, 700000, 900000, '15:00', '11:00', FALSE, 'Không cho phép mang theo trẻ nhỏ để đảm bảo không gian nghỉ dưỡng yên tĩnh tuyệt đối.', 300000, 'Chính sách hủy nghiêm ngặt dành riêng cho phòng Studio'),
                ('VIP', 'Phòng VIP cũ (Đã ngừng bán)', 2, 2, 1, 'Loại phòng VIP trước đây, hiện đã ngừng kinh doanh để nâng cấp.', FALSE, 1000000, 1500000, '14:00', '12:00', TRUE, NULL, 200000, NULL)
            """);

            Long studioId = jdbcTemplate.queryForObject(
                    "SELECT id FROM room_types WHERE code = 'STUDIO_ADULT'", Long.class);
            if (studioId != null) {
                jdbcTemplate.update("""
                    INSERT INTO room_type_cancellation_tiers (room_type_id, hours_before_check_in, refund_percent)
                    VALUES
                    (?, 48, 80),
                    (?, 0, 0)
                """, studioId, studioId);
            }
        }

        // 6. Khởi tạo tiện nghi và bảng nối room_type_amenities
        Integer amenityCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM amenities", Integer.class);
        if (amenityCount == null || amenityCount == 0) {
            jdbcTemplate.execute("""
                INSERT INTO amenities (id, code, name, icon, active) VALUES
                (1, 'DIEU_HOA',  'Điều hoà 2 chiều',    '❄️', TRUE),
                (2, 'WIFI',      'Wi-Fi tốc độ cao',    '📶', TRUE),
                (3, 'BAN_CONG',  'Ban công view đẹp',   '🌇', TRUE),
                (4, 'TIVI',      'Tivi màn hình phẳng', '📺', TRUE),
                (5, 'NONG_LANH', 'Bình nóng lạnh',      '🚿', TRUE),
                (6, 'TU_LANH',   'Tủ lạnh mini',        '🧊', TRUE)
            """);

            jdbcTemplate.execute("""
                INSERT INTO room_type_amenities (room_type_id, amenity_id)
                SELECT rt.id, a.id FROM room_types rt CROSS JOIN amenities a
                WHERE (rt.code = 'DON' AND a.code IN ('DIEU_HOA', 'WIFI', 'NONG_LANH'))
                   OR (rt.code = 'DOI' AND a.code IN ('DIEU_HOA', 'WIFI', 'TIVI', 'NONG_LANH', 'TU_LANH'))
                   OR (rt.code = 'GIA_DINH' AND a.code IN ('DIEU_HOA', 'WIFI', 'TIVI', 'NONG_LANH', 'TU_LANH', 'BAN_CONG'))
            """);
        }

        // 7. Khởi tạo danh sách phòng mẫu
        Integer roomCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM rooms", Integer.class);
        if (roomCount == null || roomCount == 0) {
            jdbcTemplate.update("""
                INSERT INTO rooms (room_number, floor, room_type, status, active)
                VALUES
                ('101', 1, 'Phòng đơn', 'TRONG_SACH', TRUE),
                ('102', 1, 'Phòng đôi', 'TRONG_SACH', TRUE),
                ('201', 2, 'Phòng đôi', 'TRONG_SACH', TRUE),
                ('301', 3, 'Phòng gia đình', 'TRONG_SACH', TRUE)
            """);
        }
    }
}
