
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    actor_email VARCHAR(255),
    user_id BIGINT,
    account_email VARCHAR(255),
    action VARCHAR(100) NOT NULL,
    result VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_user_id) REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_occurred_at
    ON audit_logs (occurred_at DESC);

CREATE INDEX idx_audit_logs_user_occurred_at
    ON audit_logs (user_id, occurred_at DESC);

CREATE INDEX idx_audit_logs_actor_occurred_at
    ON audit_logs (actor_user_id, occurred_at DESC);
