spring.application.name=homestay

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/homestay_db
spring.datasource.username=homestay_app
spring.datasource.password=mat_khau_local

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false