spring.application.name=homestay
# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/homestay_db}
spring.datasource.username=${DB_USERNAME:homestay_app}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
