
package com.ttcs.homestay.security;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;

import java.util.ArrayList;
import java.util.HashSet;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import com.ttcs.homestay.entity.Role;
import com.ttcs.homestay.entity.User;
import com.ttcs.homestay.repository.UserRepository;
import com.ttcs.homestay.service.AuditLogService;

@SpringBootTest
@AutoConfigureMockMvc
class SecurityAuthorizationIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private JwtDecoder jwtDecoder;

    @MockitoBean
    private UserRepository userRepository;

        @Autowired
        private JdbcTemplate jdbcTemplate;

        @Autowired
        private ObjectMapper objectMapper;

        @Autowired
        private AuditLogService auditLogService;

    
@BeforeEach
void setUp() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS audit_logs ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "actor_user_id BIGINT, actor_email VARCHAR(255), user_id BIGINT, "
                        + "account_email VARCHAR(255), action VARCHAR(100) NOT NULL, "
                        + "result VARCHAR(20) NOT NULL, ip_address VARCHAR(45), "
                        + "occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbcTemplate.update("DELETE FROM audit_logs");
    mockUser(101L, "RECEPTIONIST");
    mockUser(102L, "ADMIN");
    mockUser(103L, "HOUSEKEEPING");
    mockUser(104L, "OWNER");

    when(jwtDecoder.decode("receptionist-test-token"))
            .thenReturn(createJwt(101L, "RECEPTIONIST"));

    when(jwtDecoder.decode("admin-test-token"))
            .thenReturn(createJwt(102L, "ADMIN"));

    when(jwtDecoder.decode("housekeeping-test-token"))
            .thenReturn(createJwt(103L, "HOUSEKEEPING"));

    when(jwtDecoder.decode("owner-test-token"))
            .thenReturn(createJwt(104L, "OWNER"));
}


    private void mockUser(long id, String roleCode) {
        Role role = mock(Role.class);
        when(role.getCode()).thenReturn(roleCode);

        User user = mock(User.class);
        when(user.isActive()).thenReturn(true);
        when(user.isMustChangePassword()).thenReturn(false);
        when(user.getRole()).thenReturn(role);
        when(user.getTokenVersion()).thenReturn(0);

        when(userRepository.findWithRoleById(id))
                .thenReturn(Optional.of(user));
    }

    private Jwt createJwt(long userId, String roleCode) {
        Instant now = Instant.now();

        return Jwt.withTokenValue("test-token-" + userId)
                .header("alg", "HS256")
                .issuer("homestay")
                .subject(String.valueOf(userId))
                .audience(List.of("homestay-api"))
                .issuedAt(now)
                .expiresAt(now.plusSeconds(3600))
                .claim("typ", "access")
                .claim("role", roleCode)
                .claim("tv", 0)
                .build();
    }

    @Test
    void leTanTruyCapApiAdmin_biChan403() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer receptionist-test-token"
                        )
        ).andExpect(status().isForbidden());
    }

    @Test
    void housekeepingTruyCapApiAdmin_biChan403() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer housekeeping-test-token"
                        )
        ).andExpect(status().isForbidden());
    }

    @Test
    void housekeepingTruyCapApiBaoTri_biChan403() throws Exception {
        mockMvc.perform(
                patch("/api/rooms/4/maintenance")
                        .header(
                                "Authorization",
                                "Bearer housekeeping-test-token"
                        )
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}")
        ).andExpect(status().isForbidden());
    }

    @Test
    void adminDuocDiQuaLopPhanQuyen() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer admin-test-token"
                        )
        ).andExpect(status().isNotFound());
    }

        @Test
        void auditLogsChiAdminDuocXem() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk());

                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer owner-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void receptionistTruyCapTrucTiepAuditLogs_biChan403() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer receptionist-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void housekeepingTruyCapTrucTiepAuditLogs_biChan403() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer housekeeping-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void auditLogsLocTheoTaiKhoanVaPhanTrang50DongTheoGioVietNam() throws Exception {
                for (int index = 0; index < 51; index++) {
                        jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address, occurred_at) "
                                                        + "VALUES (?, ?, ?, ?, ?, ?)",
                                        "admin@homestay.local", "guest" + index + "@homestay.local", "LOGIN", "SUCCESS", "127.0.0.1",
                                        java.sql.Timestamp.from(java.time.Instant.parse("2026-09-28T18:00:00Z").plusSeconds(index)));
                }

                mockMvc.perform(get("/api/admin/audit-logs")
                                                .param("from", "2026-09-29")
                                                .param("to", "2026-09-29")
                                                .param("account", "guest")
                                                .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.size").value(50))
                                .andExpect(jsonPath("$.totalElements").value(51))
                                .andExpect(jsonPath("$.content.length()").value(50))
                                .andExpect(jsonPath("$.content[0].occurredAt").value(org.hamcrest.Matchers.endsWith("+07:00")));
        }

        @Test
        void auditLogsHaiTrangTraDu51IdDuyNhatKhongThieuHoacTrung() throws Exception {
                for (int index = 0; index < 51; index++) {
                        jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address) "
                                                        + "VALUES (?, ?, ?, ?, ?)",
                                        "admin@homestay.local", "page" + index + "@homestay.local", "LOGIN", "SUCCESS", "127.0.0.1");
                }

                List<Long> firstPageIds = auditLogIds(0);
                List<Long> secondPageIds = auditLogIds(1);
                Set<Long> allIds = new HashSet<>(firstPageIds);
                allIds.addAll(secondPageIds);

                assertThat(firstPageIds).hasSize(50);
                assertThat(secondPageIds).hasSize(1);
                assertThat(firstPageIds.size() + secondPageIds.size()).isEqualTo(51);
                assertThat(allIds).hasSize(51);
        }

        @Test
        void auditLogsKhongHoTroPutPatchDeleteVaBanGhiGocKhongDoi() throws Exception {
                jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address) "
                                + "VALUES (?, ?, ?, ?, ?)",
                        "admin@homestay.local", "immutable@homestay.local", "ROLE_CHANGED", "SUCCESS", "127.0.0.1");
                Long auditId = jdbcTemplate.queryForObject(
                        "SELECT id FROM audit_logs WHERE account_email = ?", Long.class, "immutable@homestay.local");

                mockMvc.perform(put("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());
                mockMvc.perform(patch("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());
                mockMvc.perform(delete("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());

                var original = jdbcTemplate.queryForMap(
                        "SELECT actor_email, account_email, action, result, ip_address FROM audit_logs WHERE id = ?", auditId);
                assertThat(original).containsEntry("ACTOR_EMAIL", "admin@homestay.local")
                        .containsEntry("ACCOUNT_EMAIL", "immutable@homestay.local")
                        .containsEntry("ACTION", "ROLE_CHANGED")
                        .containsEntry("RESULT", "SUCCESS")
                        .containsEntry("IP_ADDRESS", "127.0.0.1");
                assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM audit_logs WHERE id = ?", Integer.class, auditId))
                        .isEqualTo(1);
        }

        @Test
        void auditEmailSnapshotKhongDoiKhiEmailTaiKhoanThayDoi() {
                String originalEmail = "audit-demo-before@homestay.local";
                String updatedEmail = "audit-demo-after@homestay.local";
                jdbcTemplate.update("DELETE FROM users WHERE email IN (?, ?)", originalEmail, updatedEmail);
                jdbcTemplate.update("DELETE FROM roles WHERE code = 'AUDIT_TEST'");
                jdbcTemplate.update("INSERT INTO roles (code, name) VALUES ('AUDIT_TEST', 'Audit Test')");
                Long roleId = jdbcTemplate.queryForObject(
                        "SELECT id FROM roles WHERE code = 'AUDIT_TEST'", Long.class);
                jdbcTemplate.update("INSERT INTO users (full_name, email, password_hash, role_id, is_active, "
                                + "failed_login_count, must_change_password, token_version, created_at, updated_at) "
                                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                        "Audit Demo", originalEmail, "test-hash", roleId, true, 0, false, 1);
                Long userId = jdbcTemplate.queryForObject(
                        "SELECT id FROM users WHERE email = ?", Long.class, originalEmail);

                auditLogService.recordSensitiveAction(userId, originalEmail, userId, originalEmail,
                        "ROLE_CHANGED", "127.0.0.1");
                Long auditId = jdbcTemplate.queryForObject(
                        "SELECT id FROM audit_logs WHERE account_email = ?", Long.class, originalEmail);
                jdbcTemplate.update("UPDATE users SET email = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                        updatedEmail, userId);

                var savedEmails = jdbcTemplate.queryForMap(
                        "SELECT actor_email, account_email FROM audit_logs WHERE id = ?", auditId);
                assertThat(savedEmails).containsEntry("ACTOR_EMAIL", originalEmail)
                        .containsEntry("ACCOUNT_EMAIL", originalEmail);
                assertThat(jdbcTemplate.queryForObject("SELECT email FROM users WHERE id = ?", String.class, userId))
                        .isEqualTo(updatedEmail);
        }

        private List<Long> auditLogIds(int page) throws Exception {
                String response = mockMvc.perform(get("/api/admin/audit-logs")
                                        .param("page", String.valueOf(page))
                                        .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk())
                                .andReturn().getResponse().getContentAsString();
                JsonNode content = objectMapper.readTree(response).path("content");
                List<Long> ids = new ArrayList<>();
                content.forEach(entry -> ids.add(entry.path("id").asLong()));
                return ids;
        }

    @Test
    void chuaDangNhapTruyCapApiAdmin_biChan401() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
        ).andExpect(status().isUnauthorized());
    }
    @Test
void housekeepingTruyCapApiCheckIn_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/rooms/4/check-in")
                    .header(
                            "Authorization",
                            "Bearer housekeeping-test-token"
                    )
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void housekeepingTruyCapApiCheckOut_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/rooms/4/check-out")
                    .header(
                            "Authorization",
                            "Bearer housekeeping-test-token"
                    )
    ).andExpect(status().isForbidden());
}

@Test
void leTanThemLoaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/room-types")
                    .header("Authorization", "Bearer receptionist-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void housekeepingXoaLoaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            delete("/api/room-types/1")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemDanhSachLoaiPhong_duoc200() throws Exception {
    mockMvc.perform(
            get("/api/room-types")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerDuocThemLoaiPhong_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn ở bước kiểm tra dữ liệu trống (400) chứ không phải 403.
    mockMvc.perform(
            post("/api/room-types")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void adminDuocXemDanhSachLoaiPhong() throws Exception {
    mockMvc.perform(
            get("/api/room-types")
                    .header("Authorization", "Bearer admin-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerCapNhatTrangThaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            patch("/api/rooms/4/status")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void adminTruyCapApiChuaDuocCapQuyen_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/s1-04-forbidden-check")
                    .header("Authorization", "Bearer admin-test-token")
    ).andExpect(status().isForbidden());
}


}
