
package com.ttcs.homestay.security;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;

import java.util.ArrayList;
import java.util.HashSet;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import com.ttcs.homestay.entity.Role;
import com.ttcs.homestay.entity.User;
import com.ttcs.homestay.repository.UserRepository;
import com.ttcs.homestay.service.AuditLogService;

@SpringBootTest
@AutoConfigureMockMvc
class SecurityAuthorizationIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private JwtDecoder jwtDecoder;

    @MockitoBean
    private UserRepository userRepository;

        @Autowired
        private JdbcTemplate jdbcTemplate;

        @Autowired
        private ObjectMapper objectMapper;

        @Autowired
        private AuditLogService auditLogService;

@BeforeEach
void setUp() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS audit_logs ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "actor_user_id BIGINT, actor_email VARCHAR(255), user_id BIGINT, "
                        + "account_email VARCHAR(255), action VARCHAR(100) NOT NULL, "
                        + "result VARCHAR(20) NOT NULL, ip_address VARCHAR(45), "
                        + "occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbcTemplate.update("DELETE FROM audit_logs");
    mockUser(101L, "RECEPTIONIST");
    mockUser(102L, "ADMIN");
    mockUser(103L, "HOUSEKEEPING");
    mockUser(104L, "OWNER");

    when(jwtDecoder.decode("receptionist-test-token"))
            .thenReturn(createJwt(101L, "RECEPTIONIST"));

    when(jwtDecoder.decode("admin-test-token"))
            .thenReturn(createJwt(102L, "ADMIN"));

    when(jwtDecoder.decode("housekeeping-test-token"))
            .thenReturn(createJwt(103L, "HOUSEKEEPING"));

    when(jwtDecoder.decode("owner-test-token"))
            .thenReturn(createJwt(104L, "OWNER"));
}


    private void mockUser(long id, String roleCode) {
        Role role = mock(Role.class);
        when(role.getCode()).thenReturn(roleCode);

        User user = mock(User.class);
        when(user.isActive()).thenReturn(true);
        when(user.isMustChangePassword()).thenReturn(false);
        when(user.getRole()).thenReturn(role);
        when(user.getTokenVersion()).thenReturn(0);

        when(userRepository.findWithRoleById(id))
                .thenReturn(Optional.of(user));
    }

    private Jwt createJwt(long userId, String roleCode) {
        Instant now = Instant.now();

        return Jwt.withTokenValue("test-token-" + userId)
                .header("alg", "HS256")
                .issuer("homestay")
                .subject(String.valueOf(userId))
                .audience(List.of("homestay-api"))
                .issuedAt(now)
                .expiresAt(now.plusSeconds(3600))
                .claim("typ", "access")
                .claim("role", roleCode)
                .claim("tv", 0)
                .build();
    }

    @Test
    void leTanTruyCapApiAdmin_biChan403() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer receptionist-test-token"
                        )
        ).andExpect(status().isForbidden());
    }

    @Test
    void housekeepingTruyCapApiAdmin_biChan403() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer housekeeping-test-token"
                        )
        ).andExpect(status().isForbidden());
    }

    @Test
    void housekeepingTruyCapApiBaoTri_biChan403() throws Exception {
        mockMvc.perform(
                patch("/api/rooms/4/maintenance")
                        .header(
                                "Authorization",
                                "Bearer housekeeping-test-token"
                        )
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}")
        ).andExpect(status().isForbidden());
    }

    @Test
    void adminDuocDiQuaLopPhanQuyen() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
                        .header(
                                "Authorization",
                                "Bearer admin-test-token"
                        )
        ).andExpect(status().isNotFound());
    }

    @Test
    void roomManagementApiChiAdminVaOwnerDuocTruyCap() throws Exception {
        mockMvc.perform(get("/api/room-management/rooms")
                        .header("Authorization", "Bearer admin-test-token"))
                .andExpect(status().isOk());
        mockMvc.perform(get("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token"))
                .andExpect(status().isOk());
        mockMvc.perform(get("/api/room-management/rooms")
                        .header("Authorization", "Bearer receptionist-test-token"))
                .andExpect(status().isForbidden());
        mockMvc.perform(get("/api/room-management/rooms")
                        .header("Authorization", "Bearer housekeeping-test-token"))
                .andExpect(status().isForbidden());

        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer admin-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isBadRequest());
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer receptionist-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isForbidden());
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer housekeeping-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isForbidden());
    }

    @Test
    void locPhongTheoActiveVaKetHopLoaiTangTrangThaiVanHanh() throws Exception {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String roomType = "AC4-" + suffix;
        String activeRoomNumber = "AC4-" + suffix + "-A";
        String inactiveRoomNumber = "AC4-" + suffix + "-B";
        String otherFloorRoomNumber = "AC4-" + suffix + "-C";
        String otherStatusRoomNumber = "AC4-" + suffix + "-D";

        insertRoom(activeRoomNumber, 3, roomType, "TRONG_BAN", true);
        insertRoom(inactiveRoomNumber, 3, roomType, "TRONG_BAN", false);
        insertRoom(otherFloorRoomNumber, 4, roomType, "TRONG_BAN", true);
        insertRoom(otherStatusRoomNumber, 3, roomType, "TRONG_SACH", true);

        JsonNode activeRooms = objectMapper.readTree(mockMvc.perform(get("/api/room-management/rooms")
                                .param("roomType", roomType)
                                .param("active", "true")
                                .header("Authorization", "Bearer owner-test-token"))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString())
                .path("rooms");
        assertThat(activeRooms.size()).isEqualTo(3);
        activeRooms.forEach(room -> assertThat(room.path("active").asBoolean()).isTrue());

        JsonNode inactiveRooms = objectMapper.readTree(mockMvc.perform(get("/api/room-management/rooms")
                                .param("roomType", roomType)
                                .param("active", "false")
                                .header("Authorization", "Bearer owner-test-token"))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString())
                .path("rooms");
        assertThat(inactiveRooms.size()).isEqualTo(1);
        assertThat(inactiveRooms.get(0).path("roomNumber").asString()).isEqualTo(inactiveRoomNumber);
        assertThat(inactiveRooms.get(0).path("active").asBoolean()).isFalse();

        JsonNode allRooms = objectMapper.readTree(mockMvc.perform(get("/api/room-management/rooms")
                                .param("roomType", roomType)
                                .header("Authorization", "Bearer owner-test-token"))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString())
                .path("rooms");
        assertThat(allRooms.size()).isEqualTo(4);
        assertThat(allRooms.toString()).contains("\"active\":true", "\"active\":false");

        JsonNode combinedRooms = objectMapper.readTree(mockMvc.perform(get("/api/room-management/rooms")
                                .param("roomType", roomType)
                                .param("floor", "3")
                                .param("status", "TRONG_BAN")
                                .param("active", "true")
                                .header("Authorization", "Bearer owner-test-token"))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString())
                .path("rooms");
        assertThat(combinedRooms.size()).isEqualTo(1);
        assertThat(combinedRooms.get(0).path("roomNumber").asString()).isEqualTo(activeRoomNumber);
    }

    private void insertRoom(String roomNumber, int floor, String roomType, String status, boolean active) {
        jdbcTemplate.update(
                "INSERT INTO rooms (room_number, floor, room_type, status, active) VALUES (?, ?, ?, ?, ?)",
                roomNumber, floor, roomType, status, active);
    }

    @Test
    void ownerTaoXemVaKichHoatLaiPhongVatLyKemGhiChu() throws Exception {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String roomNumber = "S107" + suffix;
        String roomType = "AC1-" + suffix;
        String originalNote = "Gần thang máy";
        String updatedNote = "Đã đổi ghi chú";
        String createRequest = """
                {"roomNumber":"%s","floor":3,"roomType":"%s","note":"%s","active":false,"status":"TRONG_SACH"}
                """.formatted(roomNumber, roomType, originalNote);

        String createResponse = mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(createRequest))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.active").value(false))
                .andReturn().getResponse().getContentAsString();
        long roomId = objectMapper.readTree(createResponse).path("id").asLong();

        assertThat(jdbcTemplate.queryForObject(
                "SELECT note FROM room_notes WHERE room_id = ?", String.class, roomId))
                .isEqualTo(originalNote);

        mockMvc.perform(get("/api/room-management/rooms")
                        .param("roomType", roomType)
                        .header("Authorization", "Bearer owner-test-token"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.rooms.length()").value(1))
                .andExpect(jsonPath("$.rooms[0].id").value(roomId))
                .andExpect(jsonPath("$.rooms[0].active").value(false));

        String updateRequest = """
                {"roomNumber":"%s","floor":4,"roomType":"%s","note":"%s","active":true,"status":"TRONG_SACH","confirmWhenBookingCheckUnavailable":true}
                """.formatted(roomNumber, roomType, updatedNote);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(updateRequest))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.room.active").value(true))
                .andExpect(jsonPath("$.room.floor").value(4))
                .andExpect(jsonPath("$.note").value(updatedNote));

        mockMvc.perform(get("/api/room-management/rooms/{roomId}/note", roomId)
                        .header("Authorization", "Bearer owner-test-token"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.note").value(updatedNote));

        String deactivateRequest = """
                {"roomNumber":"%s","floor":4,"roomType":"%s","note":"%s","active":false,"status":"TRONG_SACH","confirmWhenBookingCheckUnavailable":false}
                """.formatted(roomNumber, roomType, updatedNote);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(deactivateRequest))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.room.active").value(false));

        String reactivateRequest = """
                {"roomNumber":"%s","floor":4,"roomType":"%s","note":"%s","active":true,"status":"TRONG_SACH","confirmWhenBookingCheckUnavailable":false}
                """.formatted(roomNumber, roomType, updatedNote);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(reactivateRequest))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.room.active").value(true));

        mockMvc.perform(get("/api/room-management/rooms")
                        .param("roomType", roomType)
                        .header("Authorization", "Bearer owner-test-token"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.rooms[0].floor").value(4))
                .andExpect(jsonPath("$.rooms[0].active").value(true));
    }

    @Test
    void chiLeTanDuocGoiApiGanPhong() throws Exception {
        mockMvc.perform(put("/api/bookings/987654/room")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":1}"))
                .andExpect(status().isForbidden());
        mockMvc.perform(put("/api/bookings/987654/room")
                        .header("Authorization", "Bearer receptionist-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"roomId\":1}"))
                .andExpect(status().isNotFound());
    }

    @Test
    void doiLoaiPhongKhongCoBookingModuleCanXacNhanTruocKhiLuu() throws Exception {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String roomNumber = "AC3-" + suffix;
        String originalRoomType = "Loại cũ " + suffix;
        String newRoomType = "Loại mới " + suffix;
        String originalNote = "Ghi chú ban đầu";
        String updatedNote = "Ghi chú sau xác nhận";
        String createRequest = """
                {"roomNumber":"%s","floor":3,"roomType":"%s","note":"%s","active":true}
                """.formatted(roomNumber, originalRoomType, originalNote);
        String createResponse = mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(createRequest))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString();
        long roomId = objectMapper.readTree(createResponse).path("id").asLong();

        String unconfirmedUpdate = """
                {"roomNumber":"%s","floor":3,"roomType":"%s","note":"%s","active":true,"confirmWhenBookingCheckUnavailable":false}
                """.formatted(roomNumber, newRoomType, updatedNote);
        String warningResponse = mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(unconfirmedUpdate))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.bookingCheckAvailable").value(false))
                .andExpect(jsonPath("$.warningRequired").value(true))
                .andExpect(jsonPath("$.affectedFutureBookings").value(0))
                .andExpect(jsonPath("$.room.roomType").value(originalRoomType))
                .andReturn().getResponse().getContentAsString();
        assertThat(objectMapper.readTree(warningResponse).path("warningMessage").asString())
                .contains("Chưa có module Booking")
                .contains("Hãy xác nhận tiếp tục");
        assertThat(jdbcTemplate.queryForObject(
                "SELECT room_type FROM rooms WHERE id = ?", String.class, roomId))
                .isEqualTo(originalRoomType);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT note FROM room_notes WHERE room_id = ?", String.class, roomId))
                .isEqualTo(originalNote);

        String confirmedUpdate = """
                {"roomNumber":"%s","floor":3,"roomType":"%s","note":"%s","active":true,"confirmWhenBookingCheckUnavailable":true}
                """.formatted(roomNumber, newRoomType, updatedNote);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(confirmedUpdate))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.room.roomType").value(newRoomType));

        assertThat(jdbcTemplate.queryForObject(
                "SELECT room_type FROM rooms WHERE id = ?", String.class, roomId))
                .isEqualTo(newRoomType);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT note FROM room_notes WHERE room_id = ?", String.class, roomId))
                .isEqualTo(updatedNote);
    }

    @Test
    void taoPhongTuChoiTruongBatBuocThieuHoacKhongHopLe() throws Exception {
        String missingRequiredField = """
                {"floor":1,"roomType":"Phòng đôi","note":"Ghi chú","active":true}
                """;
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(missingRequiredField))
                .andExpect(status().isBadRequest());

        String invalidFloor = """
                {"roomNumber":"INVALID-FLOOR","floor":-1,"roomType":"Phòng đôi","note":"Ghi chú","active":true}
                """;
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(invalidFloor))
                .andExpect(status().isBadRequest());

        String oversizedNote = "x".repeat(501);
        String invalidNote = """
                {"roomNumber":"INVALID-NOTE","floor":1,"roomType":"Phòng đôi","note":"%s","active":true}
                """.formatted(oversizedNote);
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(invalidNote))
                .andExpect(status().isBadRequest());

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM rooms WHERE room_number IN ('INVALID-FLOOR', 'INVALID-NOTE')", Integer.class))
                .isZero();
    }

    @Test
    void taoPhongTrungSoPhongBoQuaInactiveVaKhongPhanBietHoaThuongBiTuChoi() throws Exception {
        String roomNumber = "AC2-" + UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String originalRequest = """
                {"roomNumber":"  %s  ","floor":2,"roomType":"Phòng đôi","note":"Inactive","active":false,"status":"TRONG_SACH"}
                """.formatted(roomNumber);
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(originalRequest))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.roomNumber").value(roomNumber))
                .andExpect(jsonPath("$.active").value(false));

        String exactDuplicate = """
                {"roomNumber":"%s","floor":2,"roomType":"Phòng đôi","active":true}
                """.formatted(roomNumber);
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(exactDuplicate))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("ROOM_MANAGEMENT_ERROR"))
                .andExpect(jsonPath("$.message").value("Số phòng " + roomNumber + " đã tồn tại trong hệ thống."));

        String caseAndWhitespaceDuplicate = """
                {"roomNumber":"  %s  ","floor":2,"roomType":"Phòng đôi","active":true}
                """.formatted(roomNumber.toLowerCase(java.util.Locale.ROOT));
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(caseAndWhitespaceDuplicate))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("ROOM_MANAGEMENT_ERROR"));

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM rooms WHERE LOWER(room_number) = LOWER(?)", Integer.class, roomNumber))
                .isEqualTo(1);
    }

    @Test
    void capNhatTrungSoPhongKhacBiTuChoiVaGiuNguyenDuLieuCu() throws Exception {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String firstRoomNumber = "AC2-A-" + suffix;
        String secondRoomNumber = "AC2-B-" + suffix;
        String firstCreate = """
                {"roomNumber":"%s","floor":1,"roomType":"Phòng đôi","note":"Note gốc","active":true}
                """.formatted(firstRoomNumber);
        String secondCreate = """
                {"roomNumber":"%s","floor":2,"roomType":"Phòng đôi","note":"Phòng inactive","active":false}
                """.formatted(secondRoomNumber);
        long firstRoomId = objectMapper.readTree(mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(firstCreate))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString()).path("id").asLong();
        mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(secondCreate))
                .andExpect(status().isCreated());

        String updateRequest = """
                {"roomNumber":"%s","floor":9,"roomType":"Phòng đôi","note":"Không được lưu","active":true,"confirmWhenBookingCheckUnavailable":true}
                """.formatted(secondRoomNumber);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", firstRoomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(updateRequest))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Số phòng " + secondRoomNumber + " đã tồn tại trong hệ thống."));

        var firstRoom = jdbcTemplate.queryForMap(
                "SELECT room_number, floor, active FROM rooms WHERE id = ?", firstRoomId);
        assertThat(firstRoom).containsEntry("ROOM_NUMBER", firstRoomNumber)
                .containsEntry("FLOOR", 1)
                .containsEntry("ACTIVE", true);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT note FROM room_notes WHERE room_id = ?", String.class, firstRoomId))
                .isEqualTo("Note gốc");
    }

    @Test
    void capNhatGiuNguyenSoPhongCuaChinhPhongDuocChapNhan() throws Exception {
        String roomNumber = "AC2S-" + UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String createRequest = """
                {"roomNumber":"%s","floor":3,"roomType":"Phòng đôi","note":"Cũ","active":true}
                """.formatted(roomNumber);
        long roomId = objectMapper.readTree(mockMvc.perform(post("/api/room-management/rooms")
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(createRequest))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString()).path("id").asLong();

        String updateRequest = """
                {"roomNumber":"  %s  ","floor":3,"roomType":"Phòng đôi","note":"Mới","active":true,"confirmWhenBookingCheckUnavailable":false}
                """.formatted(roomNumber);
        mockMvc.perform(patch("/api/room-management/rooms/{roomId}", roomId)
                        .header("Authorization", "Bearer owner-test-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(updateRequest))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.room.roomNumber").value(roomNumber))
                .andExpect(jsonPath("$.note").value("Mới"));

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM rooms WHERE LOWER(room_number) = LOWER(?)", Integer.class, roomNumber))
                .isEqualTo(1);
    }

        @Test
        void auditLogsChiAdminDuocXem() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk());

                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer owner-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void receptionistTruyCapTrucTiepAuditLogs_biChan403() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer receptionist-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void housekeepingTruyCapTrucTiepAuditLogs_biChan403() throws Exception {
                mockMvc.perform(get("/api/admin/audit-logs")
                                .header("Authorization", "Bearer housekeeping-test-token"))
                                .andExpect(status().isForbidden());
        }

        @Test
        void auditLogsLocTheoTaiKhoanVaPhanTrang50DongTheoGioVietNam() throws Exception {
                for (int index = 0; index < 51; index++) {
                        jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address, occurred_at) "
                                                        + "VALUES (?, ?, ?, ?, ?, ?)",
                                        "admin@homestay.local", "guest" + index + "@homestay.local", "LOGIN", "SUCCESS", "127.0.0.1",
                                        java.sql.Timestamp.from(java.time.Instant.parse("2026-09-28T18:00:00Z").plusSeconds(index)));
                }

                mockMvc.perform(get("/api/admin/audit-logs")
                                                .param("from", "2026-09-29")
                                                .param("to", "2026-09-29")
                                                .param("account", "guest")
                                                .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.size").value(50))
                                .andExpect(jsonPath("$.totalElements").value(51))
                                .andExpect(jsonPath("$.content.length()").value(50))
                                .andExpect(jsonPath("$.content[0].occurredAt").value(org.hamcrest.Matchers.endsWith("+07:00")));
        }

        @Test
        void auditLogsHaiTrangTraDu51IdDuyNhatKhongThieuHoacTrung() throws Exception {
                for (int index = 0; index < 51; index++) {
                        jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address) "
                                                        + "VALUES (?, ?, ?, ?, ?)",
                                        "admin@homestay.local", "page" + index + "@homestay.local", "LOGIN", "SUCCESS", "127.0.0.1");
                }

                List<Long> firstPageIds = auditLogIds(0);
                List<Long> secondPageIds = auditLogIds(1);
                Set<Long> allIds = new HashSet<>(firstPageIds);
                allIds.addAll(secondPageIds);

                assertThat(firstPageIds).hasSize(50);
                assertThat(secondPageIds).hasSize(1);
                assertThat(firstPageIds.size() + secondPageIds.size()).isEqualTo(51);
                assertThat(allIds).hasSize(51);
        }

        @Test
        void auditLogsKhongHoTroPutPatchDeleteVaBanGhiGocKhongDoi() throws Exception {
                jdbcTemplate.update("INSERT INTO audit_logs (actor_email, account_email, action, result, ip_address) "
                                + "VALUES (?, ?, ?, ?, ?)",
                        "admin@homestay.local", "immutable@homestay.local", "ROLE_CHANGED", "SUCCESS", "127.0.0.1");
                Long auditId = jdbcTemplate.queryForObject(
                        "SELECT id FROM audit_logs WHERE account_email = ?", Long.class, "immutable@homestay.local");

                mockMvc.perform(put("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());
                mockMvc.perform(patch("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());
                mockMvc.perform(delete("/api/admin/audit-logs/{id}", auditId)
                                .header("Authorization", "Bearer admin-test-token"))
                        .andExpect(status().isNotFound());

                var original = jdbcTemplate.queryForMap(
                        "SELECT actor_email, account_email, action, result, ip_address FROM audit_logs WHERE id = ?", auditId);
                assertThat(original).containsEntry("ACTOR_EMAIL", "admin@homestay.local")
                        .containsEntry("ACCOUNT_EMAIL", "immutable@homestay.local")
                        .containsEntry("ACTION", "ROLE_CHANGED")
                        .containsEntry("RESULT", "SUCCESS")
                        .containsEntry("IP_ADDRESS", "127.0.0.1");
                assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM audit_logs WHERE id = ?", Integer.class, auditId))
                        .isEqualTo(1);
        }

        @Test
        void auditEmailSnapshotKhongDoiKhiEmailTaiKhoanThayDoi() {
                String originalEmail = "audit-demo-before@homestay.local";
                String updatedEmail = "audit-demo-after@homestay.local";
                jdbcTemplate.update("DELETE FROM users WHERE email IN (?, ?)", originalEmail, updatedEmail);
                jdbcTemplate.update("DELETE FROM roles WHERE code = 'AUDIT_TEST'");
                jdbcTemplate.update("INSERT INTO roles (code, name) VALUES ('AUDIT_TEST', 'Audit Test')");
                Long roleId = jdbcTemplate.queryForObject(
                        "SELECT id FROM roles WHERE code = 'AUDIT_TEST'", Long.class);
                jdbcTemplate.update("INSERT INTO users (full_name, email, password_hash, role_id, is_active, "
                                + "failed_login_count, must_change_password, token_version, created_at, updated_at) "
                                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                        "Audit Demo", originalEmail, "test-hash", roleId, true, 0, false, 1);
                Long userId = jdbcTemplate.queryForObject(
                        "SELECT id FROM users WHERE email = ?", Long.class, originalEmail);

                auditLogService.recordSensitiveAction(userId, originalEmail, userId, originalEmail,
                        "ROLE_CHANGED", "127.0.0.1");
                Long auditId = jdbcTemplate.queryForObject(
                        "SELECT id FROM audit_logs WHERE account_email = ?", Long.class, originalEmail);
                jdbcTemplate.update("UPDATE users SET email = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                        updatedEmail, userId);

                var savedEmails = jdbcTemplate.queryForMap(
                        "SELECT actor_email, account_email FROM audit_logs WHERE id = ?", auditId);
                assertThat(savedEmails).containsEntry("ACTOR_EMAIL", originalEmail)
                        .containsEntry("ACCOUNT_EMAIL", originalEmail);
                assertThat(jdbcTemplate.queryForObject("SELECT email FROM users WHERE id = ?", String.class, userId))
                        .isEqualTo(updatedEmail);
        }

        private List<Long> auditLogIds(int page) throws Exception {
                String response = mockMvc.perform(get("/api/admin/audit-logs")
                                        .param("page", String.valueOf(page))
                                        .header("Authorization", "Bearer admin-test-token"))
                                .andExpect(status().isOk())
                                .andReturn().getResponse().getContentAsString();
                JsonNode content = objectMapper.readTree(response).path("content");
                List<Long> ids = new ArrayList<>();
                content.forEach(entry -> ids.add(entry.path("id").asLong()));
                return ids;
        }

    @Test
    void chuaDangNhapTruyCapApiAdmin_biChan401() throws Exception {
        mockMvc.perform(
                get("/api/admin/authorization-test")
        ).andExpect(status().isUnauthorized());
    }
    @Test
void housekeepingTruyCapApiCheckIn_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/rooms/4/check-in")
                    .header(
                            "Authorization",
                            "Bearer housekeeping-test-token"
                    )
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void housekeepingTruyCapApiCheckOut_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/rooms/4/check-out")
                    .header(
                            "Authorization",
                            "Bearer housekeeping-test-token"
                    )
    ).andExpect(status().isForbidden());
}

@Test
void leTanThemLoaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/room-types")
                    .header("Authorization", "Bearer receptionist-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void housekeepingXoaLoaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            delete("/api/room-types/1")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemDanhSachLoaiPhong_duoc200() throws Exception {
    mockMvc.perform(
            get("/api/room-types")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerDuocThemLoaiPhong_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn ở bước kiểm tra dữ liệu trống (400) chứ không phải 403.
    mockMvc.perform(
            post("/api/room-types")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void adminDuocXemDanhSachLoaiPhong() throws Exception {
    mockMvc.perform(
            get("/api/room-types")
                    .header("Authorization", "Bearer admin-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerCapNhatTrangThaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            patch("/api/rooms/4/status")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void adminTruyCapApiChuaDuocCapQuyen_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/s1-04-forbidden-check")
                    .header("Authorization", "Bearer admin-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanThemTienNghi_biChan403() throws Exception {
    mockMvc.perform(
            post("/api/amenities")
                    .header("Authorization", "Bearer receptionist-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void buongPhongBoTienNghiKhoiLoaiPhong_biChan403() throws Exception {
    mockMvc.perform(
            delete("/api/room-types/1/amenities/1")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemDanhSachTienNghi_duoc200() throws Exception {
    mockMvc.perform(
            get("/api/amenities")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerThemTienNghi_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn ở bước kiểm tra dữ liệu trống (400) chứ không phải 403.
    mockMvc.perform(
            post("/api/amenities")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void adminSuaThamSo_biChan403() throws Exception {
    // S1-09: ma trận "Bảng giá và chính sách huỷ" cho Admin chỉ xem (R)
    mockMvc.perform(
            put("/api/settings")
                    .header("Authorization", "Bearer admin-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemLichSuThamSo_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/settings/history")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void buongPhongXemThamSo_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/settings")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void ownerSuaThamSo_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn ở bước kiểm tra dữ liệu trống (400) chứ không phải 403.
    mockMvc.perform(
            put("/api/settings")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void adminThemGiaDe_biChan403() throws Exception {
    // S2-02: ma trận "Bảng giá và chính sách huỷ" cho Admin chỉ xem (R)
    mockMvc.perform(
            post("/api/price-overrides")
                    .header("Authorization", "Bearer admin-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXoaGiaDe_biChan403() throws Exception {
    mockMvc.perform(
            delete("/api/price-overrides/1")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void buongPhongXemGiaDe_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/price-overrides")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemGiaDe_duoc200() throws Exception {
    mockMvc.perform(
            get("/api/price-overrides")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isOk());
}

@Test
void ownerThemGiaDe_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn ở bước kiểm tra dữ liệu trống (400) chứ không phải 403.
    mockMvc.perform(
            post("/api/price-overrides")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void buongPhongXemGiaTungDem_biChan403() throws Exception {
    mockMvc.perform(
            get("/api/pricing/quote")
                    .header("Authorization", "Bearer housekeeping-test-token")
    ).andExpect(status().isForbidden());
}

@Test
void leTanXemGiaTungDem_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn vì thiếu tham số (400) chứ không phải 403.
    mockMvc.perform(
            get("/api/pricing/quote")
                    .header("Authorization", "Bearer receptionist-test-token")
    ).andExpect(status().isBadRequest());
}

@Test
void leTanXemTruocGiaDe_biChan403() throws Exception {
    // Xem trước chỉ dùng trong form thêm/sửa, nên chỉ Chủ homestay được gọi.
    mockMvc.perform(
            post("/api/price-overrides/preview")
                    .header("Authorization", "Bearer receptionist-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isForbidden());
}

@Test
void ownerXemTruocGiaDe_quaPhanQuyen() throws Exception {
    // Qua được phân quyền, bị chặn vì thiếu loại phòng và ngày (400) chứ không phải 403.
    mockMvc.perform(
            post("/api/price-overrides/preview")
                    .header("Authorization", "Bearer owner-test-token")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void khachChuaDangNhapXemLoaiPhongDatDuoc_duoc200() throws Exception {
    // S2-07: trang đặt phòng công khai, không gửi token.
    mockMvc.perform(get("/api/public/room-types")).andExpect(status().isOk());
}

@Test
void khachChuaDangNhapTraCuuPhong_duoc200() throws Exception {
    java.time.LocalDate checkIn = java.time.LocalDate.now().plusDays(10);
    mockMvc.perform(get("/api/public/rooms/search")
                    .param("checkIn", checkIn.toString())
                    .param("checkOut", checkIn.plusDays(3).toString())
                    .param("guestCount", "2"))
            .andExpect(status().isOk());
}

@Test
void khachChuaDangNhapGuiDatPhong_quaPhanQuyen() throws Exception {
    // Không bị 401/403; bị chặn vì thiếu thông tin (400).
    mockMvc.perform(
            post("/api/public/bookings")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content("{}")
    ).andExpect(status().isBadRequest());
}

@Test
void khachChuaDangNhapXemTamTinh_quaPhanQuyen() throws Exception {
    // S2-06: không bị 401/403; bị chặn vì thiếu loại phòng và ngày (400).
    mockMvc.perform(get("/api/public/quote")).andExpect(status().isBadRequest());
}
}
